# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20170710_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='artistoverview',
            old_name='ArtistBio',
            new_name='Bio',
        ),
    ]
