# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20170711_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistoverview',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
